config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users , path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'slangs#index'
  resources :slangs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slang.rb
class Slang < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates_presence_of :username

         has_many :slangs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

        devise_parameter_sanitizer.permit(:account_update, keys: [:username])

    end
end

app/controllers/slangs_controller.rb
class SlangsController < ApplicationController
  before_action :set_slang, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :new, :destroy, :edit, :updte]

  # GET /slangs
  # GET /slangs.json
  def index
    @slangs = Slang.all.order("created_at DESC")
    
  end

  # GET /slangs/1
  # GET /slangs/1.json
  def show
  end

  # GET /slangs/new
  def new
    @slang = Slang.new
  end

  # GET /slangs/1/edit
  def edit
  end

  # POST /slangs
  # POST /slangs.json
  def create
    # @slang = Slang.new(slang_params)
    @slang = Slang.new(slang_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @slang.save
        format.html { redirect_to @slang, notice: 'Slang was successfully created.' }
        format.json { render :show, status: :created, location: @slang }
      else
        format.html { render :new }
        format.json { render json: @slang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slangs/1
  # PATCH/PUT /slangs/1.json
  def update
    respond_to do |format|
      if @slang.update(slang_params)
        format.html { redirect_to @slang, notice: 'Slang was successfully updated.' }
        format.json { render :show, status: :ok, location: @slang }
      else
        format.html { render :edit }
        format.json { render json: @slang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slangs/1
  # DELETE /slangs/1.json
  def destroy
    @slang.destroy
    respond_to do |format|
      format.html { redirect_to slangs_url, notice: 'Slang was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slang
      @slang = Slang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slang_params
      params.require(:slang).permit(:slang, :meaning, :usage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slangs_helper.rb
module SlangsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Islangs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">iSlang Knowledge base</span>
</nav>
       <% if current_user %>
       <%= link_to 'logout' , destroy_user_session_path, method: :delete %>
       <% end %>
       <div class="container-fluid">
    <%= yield %>
    </div>

    <footer class="app-footer">
  <div>
    <a href="http://github.com/iphytech">Iphy</a>
    <span>&copy; 2019 | All right reserved </span>
  </div>

</footer>
  </body>
</html>

app/views/slangs/_form.html.erb
<%= form_with(model: slang, local: true) do |form| %>
  <% if slang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slang.errors.count, "error") %> prohibited this slang from being saved:</h2>

      <ul>
      <% slang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :slang %>
    <%= form.text_field :slang %>
  </div>

  <div class="field">
    <%= form.label :meaning %>
    <%= form.text_area :meaning %>
  </div>

  <div class="field">
    <%= form.label :usage %>
    <%= form.text_area :usage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slangs/_search.html.erb
<div id="search" class="text-center">
<%= form_tag  "#", method: :get, id: "search_form" do %>

<div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-4">
    <%= text_field_tag :search, params[:slang], placeholder: "Lookup slang", autofocus: true, class: "form-control search-box input-lg" %>
    </div>

    <div class="col-md-2">
    <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
    <i class="fa fa-search"></i> Look up a stock
    <% end %>
    </div>
</div>

<% end %>
</div>

app/views/slangs/edit.html.erb
<h1>Editing Slang</h1>

<%= render 'form', slang: @slang %>

<%= link_to 'Show', @slang %> |
<%= link_to 'Back', slangs_path %>

app/views/slangs/index.html.erb
<p id="notice"><%= notice %></p>
<%=  render 'search' %>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Slang</th>
      <th scope="col">Meaning</th>
      <th scope="col">Usage</th>
      <th scope="col">By</th>
      <th scope="col">Added</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @slangs.each do |slang| %>
      <tr>
        <td scope="row"><%= slang.slang %></td>
        <td><%= slang.meaning %></td>
        <td><%= slang.usage %></td>
        <td><%= slang.user.username %></td> 
        <td scope="row"><%= distance_of_time_in_words(slang.created_at, Time.now) %> ago</td>
        <% if current_user %>
        <td><%= link_to 'Show', slang %></td>
        <td><%= link_to 'Edit', edit_slang_path(slang) %></td>
        <td><%= link_to 'Destroy', slang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<%= link_to 'New Slang', new_slang_path %>
<% end %>

app/views/slangs/new.html.erb
<h1>New Slang</h1>

<%= render 'form', slang: @slang %>

<%= link_to 'Back', slangs_path %>

app/views/slangs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slang:</strong>
  <%= @slang.slang %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @slang.meaning %>
</p>

<p>
  <strong>Usage:</strong>
  <%= @slang.usage %>
</p>

<% if current_user %>

<%= link_to 'Edit', edit_slang_path(@slang) %> |

<%= link_to 'Back', slangs_path %>
<% else %>
<%= link_to 'Back', slangs_path %>
<% end %>